### ISSUE TITLE
Idea: Add temperature scale to TODO constants

### ISSUE THREAD

**Issue by CallMeRZIBI** [yaylinda/scriptable#11]
It would be nice if you could decide of you wanna get degrees F or degrees C.

**Comment by drikkes** [comment]
There is no way to change from Fahrenheit to Celsius scale? Or do I have to go to the OpenWeather settings? Couldn‘t find anything there.

**Comment by yaylinda** [comment]
Ah yeah, the emoji mapping uses Fahrenheit values unfortunately, so if you get the openweatherapi to return the data in Celsius, you'll need to update the "getEmoji()" function as well. 

I think this is pretty do-able using a flag, and just multiplication, so I'll see if i can get to it. 

Otherwise, feel free to submit a PR if you already have it!
