### ISSUE TITLE
AggregatedDailyLogs wrong date in file name

### ISSUE THREAD

**Issue by harrtho** [yaylinda/scriptable#13]
Hey,

first of all great work :)! I was playing a little around with your AggregatedDailyLogs script. When I checked the saved json files I recognized that the date in the file name is one month behind. Today is the 2021_11_02 but the file for today is named 2021_10_02.

I tried to find the bug but I was not really successful. Please find attached two screen shots from yesterday that should make it more clear what I mean:

![IMG_2016](https://user-images.githubusercontent.com/4960192/139950520-eeb183de-1fff-43f2-a37d-fb74deee8644.jpg)

![IMG_2017](https://user-images.githubusercontent.com/4960192/139950788-9341f70d-59ca-46bf-9699-6aed130521ca.jpg)

**Comment by yaylinda** [comment]
hey there! sorry for the SUPER late reply to your message!

regarding the date thing... ah yeah it's actually "correct", although i can see how it's confusing. in javascript's date object, the month is 0-indexed. meaning, instead of counting from 1, 2, 3..., you start counting from 0, 1, 2... 

here's some documentation about it, if you're curious to learn more: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth

**Comment by harrtho** [comment]
Haha ok, I hadn't expected that and that's why I never "googled" it. Thank you, even for the late reply :)
